Update Pathlib usage and docstrings
brainglobe/brainglobe-utils pull request #68
Opened 2024-04-10 11:08 UTC by willGraham01

## Description

**What is this PR**

- [ ] Bug fix
- [ ] Addition of a new feature
- [x] Other

**Why is this PR needed?**

Standardises our imports of `pathlib` `Path`s and avoids importing the whole module when we only need the `Path` class.

**What does this PR do?**

- Standardises our import of `Path` to `from pathlib import Path` across the package.
- Updates / adds docstrings to a few functions that reply on `Path` inputs.

## References

No issues, but picked up on in a comment on https://github.com/brainglobe/brainglobe-utils/pull/65#issuecomment-2046963476

## How has this PR been tested?

Tests pass locally. No package functionality should be changed, either.

## Is this a breaking change?

No.

## Does this PR require an update to the documentation?

N/A

## Checklist:

- [x] The code has been tested locally
- [x] Tests have been added to cover all new functionality (unit & integration)
- [x] The documentation has been updated to reflect any changes
- [x] The code has been formatted with [pre-commit](https://pre-commit.com/)

2024-04-10 11:19 UTC, willGraham01 commented
CodeCov doesn't like my `TYPE_CHECKING` imports in files where we don't actually need to instantiate a `Path` object.

Happy to change those to regular imports on reviewer's request to avoid the red-cross-of-doom :sweat_smile:

2024-04-10 13:05 UTC, K-Meech requested changes
Looks good to me! Just a few minor changes I noted in the comments. For the `TYPE_CHECKING` imports I wonder if there's a way to exclude these lines from `codecov` [as `coverage` can do](https://github.com/nedbat/coveragepy/issues/831#issuecomment-517778185)? Otherwise, probably best to just use standard imports to avoid the red cross :sweat_smile:

2024-04-10 13:31 UTC, willGraham01 commented on brainglobe_utils/IO/yaml.py
> +) -> Dict[str, Any]:
Yeah that's true, forgot yaml sections don't have to be multi-field. `Any` it is (as much as it pains me to have an `Any` typehint :joy: )

2024-04-10 14:06 UTC, K-Meech requested changes
Looks good! For consistency, I just highlighted a few areas where quotes are no longer needed around the types.

2024-04-10 14:06 UTC, K-Meech commented on brainglobe_utils/IO/surfaces.py
> +    marching_cubes_out: Tuple["NDArray"], output_file: Union[str, "Path"]
```suggestion
    marching_cubes_out: Tuple[NDArray], output_file: Union[str, Path]
```

2024-04-10 14:06 UTC, K-Meech commented on brainglobe_utils/IO/yaml.py
> +    output_file: Union[str, "Path"],
```suggestion
    output_file: Union[str, Path],
```

2024-04-10 14:06 UTC, K-Meech commented on brainglobe_utils/general/pathlib.py
> +def append_to_pathlib_stem(path: "Path", string_to_append: str):
```suggestion
def append_to_pathlib_stem(path: Path, string_to_append: str):
```

2024-04-10 14:06 UTC, K-Meech commented on brainglobe_utils/general/string.py
> +    file: "Path",
```suggestion
    file: Path,
```

2024-04-10 14:06 UTC, K-Meech commented on brainglobe_utils/IO/yaml.py
> +def read_yaml_section(yaml_file: Union[str, "Path"], section: str) -> Any:
```suggestion
def read_yaml_section(yaml_file: Union[str, Path], section: str) -> Any:
```

2024-04-10 14:06 UTC, K-Meech commented on brainglobe_utils/IO/yaml.py
> +def open_yaml(yaml_file: Union[str, "Path"]) -> Dict[str, Any]:
```suggestion
def open_yaml(yaml_file: Union[str, Path]) -> Dict[str, Any]:
```

2024-04-11 08:09 UTC, willGraham01 commented
> where quotes are no longer needed around the types

VSCode linter why have you forsaken me :sob:

2024-04-11 08:51 UTC, K-Meech approved these changes
Looks good! I'll go ahead and merge now.

2024-04-11 08:51 UTC, merged